export const ModalTypes = {
  ALERT_MODAL: 'ALERT_MODAL',
  ASK_FOR_ACCESS_MODAL: 'ASK_FOR_ACCESS_MODAL',
  ACCESS_OPTIONS_MODAL: 'ACCESS_OPTIONS_MODAL',
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
}
